config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/contact'

  scope '(:locale)' do
    root                     'static_pages#home'
    get       'help'      => 'static_pages#help'
    resources :suppliers
  end

end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  scope :search, ->(keyword){ where('keywords LIKE ?', "%#{keyword.downcase}%") if keyword.present? }

  before_save :set_keywords

  validates :nick, presence: true,
                    uniqueness: { case_sensitive: false }

  protected

    def set_keywords
      self.keywords = [self.nick, name, tax_id, address1, address2, city, state, zip, country,
        contact, mobile, phone, email, webpage].map(&:downcase).join(' ')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_i18n_locale_from_params

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
    def set_i18n_locale_from_params
      if params[:locale]
        if I18n.available_locales.map(&:to_s).include?(params[:locale])
          I18n.locale = params[:locale]
        else
          flash.now[:notice] =
            "#{params[:locale]} translation not available"
          logger.error flash.now[:notice]
        end
      end
    end

    def default_url_options
      { locale: I18n.locale }
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def help
  end

  def home
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  def index
    @suppliers = Supplier.search(params[:keyword])
  end

  def show
  end

  def new
    @supplier = Supplier.new
  end

  def edit
  end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      flash[:success] = "Supplier was successfully created."
      redirect_to suppliers_url
    else
      render :new
    end
  end

  def update
    if @supplier.update(supplier_params)
      flash[:success] = "Supplier was successfully updated."
      redirect_to @supplier
    else
      render :edit
    end
  end

  def destroy
    @supplier.destroy
    flash[:success] = "Supplier was successfully destroyed."
    redirect_to suppliers_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:nick, :name, :tax_id, :address1, :address2, :city, :state, :zip, :country, :contact, :mobile, :phone, :email, :webpage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Rails App powered by <a href="mailto:efiguerc@gmail.com">Edgar Figueroa</a>
  </small>
  <nav>
    <ul><li><%= link_to t('.contact'), '#' %></li></ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="    navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "huell - itas", root_path, id: "logo" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to t('.products'),  '#' %></li>
        <li><%= link_to Supplier.model_name.human(count: 2), suppliers_path %></li>
        <li><%= link_to t('.help'),      help_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= I18n.locale %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% LANGUAGES.each do |language, locale|%>
              <li><%= link_to language, locale: locale %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Huell-itas Rails Web App">
<meta name="author" content="Edgar Figueroa">
<%= favicon_link_tag "favicon.ico" %>
<title>HuellItas</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>

  <%= yield %>

  <%= render "layouts/footer" %>
</div><!-- /.container -->

</body>
</html>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p><%= t('.message') %></p>

app/views/static_pages/home.html.erb
<div class="row">
<div class="col-md-6 col-xs-12">
  <img id="logo-big" src=<%= image_url "huellitas_logo_big.jpg" %> class="img-responsive" alt="Huell-itas S.A. de C.V.">
</div>
<div class="center jumbotron img-responsive col-md-6 col-xs-12">
  <h1><%= t('.welcome') %></h1>
  <h2><%= t('.welcome_message').html_safe %></h2>
  <%= link_to t('.start'), "#", class: "btn btn-lg btn-primary" %>
</div>
</div>

app/views/suppliers/_form.html.erb
<%= form_for(@supplier, html: {class: "form-horizontal"}) do |f| %>
  <% if @supplier.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@supplier.errors.count, "error") %>.
      </div>
      <ul>
        <% @supplier.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% label_col, field_col = "col-md-3", "col-md-9" %>

  <div class="row">
  <div class="col-md-6">
  <div class="field form-group">
    <%= f.label :nick, class: "col-md-3 control-label text-right" %>
    <div class="col-md-9">
      <%= f.text_field :nick, class: "form-control" %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :address1, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :address1, class: "form-control" %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :address2, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :address2, class: "form-control" %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :city, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :state, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :state, class: "form-control" %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :zip, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :zip, class: "form-control" %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :country, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :country, class: "form-control" %>
    </div>
  </div>
  </div>
  <div class="col-md-6">
   <div class="field form-group">
    <%= f.label :name, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :tax_id, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :tax_id, class: "form-control" %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :contact, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :contact, class: "form-control" %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :mobile, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :mobile, class: "form-control" %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :phone, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :phone, class: "form-control" %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :email, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="field form-group">
    <%= f.label :webpage, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= f.text_field :webpage, class: "form-control" %>
    </div>
  </div>
  </div>
  </div>
  <br>
  <div class="row">
  <div class="actions">
    <%= f.submit t('.save', model_name: Supplier.model_name.human()), class: "btn btn-lg btn-primary col-xs-offset-4 col-xs-4 col-md-offset-4 col-md-4" %>
  </div>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editing Supplier</h1>

<%= render 'form' %>

<%= link_to t('.back'), @supplier %>

app/views/suppliers/index.html.erb
<h1><%= Supplier.model_name.human(count: 2) %><small>
  <%= link_to t('.new'), new_supplier_path %>
</small></h1>

<form>
  <div class="input-group col-md-offset-9 col-md-3 col-xs-12">
    <%= search_field_tag "keyword", params[:keyword], class: "form-control", placeholder: t('.search') %>
  </div><!-- /input-group -->
</form>
<br>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th><%= t('.name') %></th>
      <th><%= t('.contact') %></th>
      <th class="hidden-xs"><%= t('.address') %></th>
    </tr>
  </thead>

  <tbody>
    <% @suppliers.each do |supplier| %>
      <tr>
        <td>
          <p><b><%= link_to supplier.nick, supplier %></b></p>
          <p class="hidden-xs">
            <%= supplier.name %><br>
            <%= supplier.tax_id %>
          </p>
        </td>
        <td><p>
          <% unless supplier.contact.empty? %> <%= supplier.contact %> <br> <% end %>
          <% unless supplier.mobile.empty? %> <%= supplier.mobile %> <br> <% end %>
          <% unless supplier.phone.empty? %> <%= supplier.phone %> <br> <% end %>
          <% unless supplier.email.empty? %> <%= supplier.email %> <br> <% end %>
          <% unless supplier.webpage.empty? %> <%= supplier.webpage %> <br> <% end %>
        </p></td>
        <td class="hidden-xs"><p>
          <%= supplier.address1 %><br>
          <%= supplier.address2 %><br>
          <%= supplier.city %><br>
          <%= supplier.state %><br>
          <%= supplier.zip %>,
          <%= supplier.country %>
        </p></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/suppliers/new.html.erb
<h1><%= t '.title', model_name: Supplier.model_name.human() %></h1>
<br>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @supplier.nick %></h1>

<div class="row">
<dl class="dl-horizontal">
  <div class="col-md-6 col-xs-12">
    <dt><h5><strong><%= Supplier.human_attribute_name("name") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.name %></h4></dd>
    <dt><h5><strong><%= Supplier.human_attribute_name("tax_id") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.tax_id %></h4></dd>
    <p><br></p>
    <dt><h5><strong><%= Supplier.human_attribute_name("contact") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.contact %></h4></dd>
    <dt><h5><strong><%= Supplier.human_attribute_name("mobile") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.mobile %></h4></dd>
    <dt><h5><strong><%= Supplier.human_attribute_name("phone") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.phone %></h4></dd>
    <dt><h5><strong><%= Supplier.human_attribute_name("email") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.email %></h4></dd>
    <dt><h5><strong><%= Supplier.human_attribute_name("webpage") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.webpage %></h4></dd>
  </div>
  <div class="col-md-6 col-xs-12">
    <p><br></p>
    <dt><h5><strong><%= Supplier.human_attribute_name("address1") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.address1 %></h4></dd>
    <dt><h5><strong><%= Supplier.human_attribute_name("address2") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.address2 %></h4></dd>
    <dt><h5><strong><%= Supplier.human_attribute_name("city") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.city %></h4></dd>
    <dt><h5><strong><%= Supplier.human_attribute_name("state") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.state %></h4></dd>
    <dt><h5><strong><%= Supplier.human_attribute_name("zip") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.zip %></h4></dd>
    <dt><h5><strong><%= Supplier.human_attribute_name("country") %>:</strong></h5></dt>
    <dd><h4><%= @supplier.country %></h4></dd>
  </div>
</dl>
</div>
<p><br></p>

<%= link_to t('.edit'), edit_supplier_path(@supplier) %> |
<%= link_to t('.destroy'), @supplier, method: :delete, data: { confirm: t('.confirm') } %>